FACE_EDITOR_LAYOUT_DATA = {
    '': {
        'FaceEditorEnableToggle': {
            'level': 1,
            'label': 'Enable Face Editor',
            'default': False,
            'help': 'Enable Face Editor.'
        },
        'FaceEditorTypeSelection': {
            'level': 2,
            'label': 'Face Editor Type',
            #'options': ['Human-Face', 'Animal-Face'],
            'options': ['Human-Face'],
            'default': 'Human-Face',
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Select the target type to be edited in Face Editor.'
        },
        'CropScaleDecimalSlider': {
            'level': 2,
            'label': 'Crop Scale',
            'min_value': '1.80',
            'max_value': '3.20',
            'default': '2.50',
            'step': 0.05,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes source crop scale.'
        },
        'EyesOpenRatioDecimalSlider': {
            'level': 2,
            'label': 'Eyes Close <--> Open Ratio',
            'min_value': '-0.80',
            'max_value': '0.80',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the opening of the eyes.'
        },
        'LipsOpenRatioDecimalSlider': {
            'level': 2,
            'label': 'Lips Close <--> Open Ratio',
            'min_value': '-0.80',
            'max_value': '0.80',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the opening of the lips.'
        },
        'HeadPitchSlider': {
            'level': 2,
            'label': 'Head Pitch',
            'min_value': '-15',
            'max_value': '15',
            'default': '0',
            'step': 1,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the opening of the lips.'
        },
        'HeadYawSlider': {
            'level': 2,
            'label': 'Head Yaw',
            'min_value': '-15',
            'max_value': '15',
            'default': '0',
            'step': 1,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the head yaw.'
        },
        'HeadRollSlider': {
            'level': 2,
            'label': 'Head Roll',
            'min_value': '-15',
            'max_value': '15',
            'default': '0',
            'step': 1,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the head roll.'
        },
        'XAxisMovementDecimalSlider': {
            'level': 2,
            'label': 'X-Axis Movement',
            'min_value': '-0.19',
            'max_value': '0.19',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the head direction x-axis.'
        },
        'YAxisMovementDecimalSlider': {
            'level': 2,
            'label': 'Y-Axis Movement',
            'min_value': '-0.19',
            'max_value': '0.19',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the head direction y-axis.'
        },
        'ZAxisMovementDecimalSlider': {
            'level': 2,
            'label': 'Z-Axis Movement',
            'min_value': '-0.90',
            'max_value': '1.20',
            'default': '1.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the head direction z-axis.'
        },
        'MouthPoutingDecimalSlider': {
            'level': 2,
            'label': 'Mouth Pouting',
            'min_value': '-0.09',
            'max_value': '0.09',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Pouting the mouth.'
        },
        'MouthPursingDecimalSlider': {
            'level': 2,
            'label': 'Mouth Pursing',
            'min_value': '-20.00',
            'max_value': '15.00',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Pursing the mouth.'
        },
        'MouthGrinDecimalSlider': {
            'level': 2,
            'label': 'Mouth Grin',
            'min_value': '0.00',
            'max_value': '15.00',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the mouth grin.'
        },
        'LipsCloseOpenSlider': {
            'level': 2,
            'label': 'Lips Close <--> Open Value',
            'min_value': '-90',
            'max_value': '120',
            'default': '0',
            'step': 1,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the closing or opening of the lips.'
        },
        'MouthSmileDecimalSlider': {
            'level': 2,
            'label': 'Mouth Smile',
            'min_value': '-0.30',
            'max_value': '1.30',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the mouth smile.'
        },
        'EyeWinkDecimalSlider': {
            'level': 2,
            'label': 'Eye Wink',
            'min_value': '0.00',
            'max_value': '39.00',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Winking eye.'
        },
        'EyeBrowsDirectionDecimalSlider': {
            'level': 2,
            'label': 'EyeBrows Direction',
            'min_value': '-30.00',
            'max_value': '30.00',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the eyebrows direction.'
        },
        'EyeGazeHorizontalDecimalSlider': {
            'level': 2,
            'label': 'EyeGaze Horizontal',
            'min_value': '-30.00',
            'max_value': '30.00',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the horizontal eyegaze direction.'
        },
        'EyeGazeVerticalDecimalSlider': {
            'level': 2,
            'label': 'EyeGaze Vertical',
            'min_value': '-63.00',
            'max_value': '63.00',
            'default': '0.00',
            'step': 0.01,
            'decimals': 2,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Changes the vertical eyegaze direction.'
        },
        'FaceEditorBlendAmountSlider': {
            'level': 2,
            'label': 'Blend Amount',
            'min_value': '0',
            'max_value': '100',
            'default': '5',
            'step': 1,
            'parentToggle': 'FaceEditorEnableToggle',
            'requiredToggleValue': True,
            'help': 'Blend amount.'
        },
    }
}